button:
 -
  type: "view"
  name: "外卖预定"
  url:  "http://jiancan.me/wx.html"
 -
  name: "堂食"
  sub_button:
   -
    type: "click"
    name: "扫描下单"
    key:  "BADGE_IN_OUT"
   -
    type: "click"
    name: "年假余额"
    key:  "ANNUAL_LEAVE"
 -
   name: "我的"
   sub_button:
    -
     type: "view"
     name: "绑定手机"
     url:  "http://jiancan.me/"
    -
     type: "view"
     name: "下载APP"
     url:  "http://jiancan.me/"
