default: &default
  appid: "wx799b2d765bf4b9ac"
  secret: "12cb0b486187ff17e90a05edbdfcd837"
  token:  "ljh861117wss900331"
  access_token: "/var/tmp/wechat_access_token"

production:
  appid: <%= ENV['wechat_app_id'] %>
  secret: <%= ENV['wechat_app_secret'] %>
  token:   <%= ENV['wechat_token'] %>
  access_token:  <%= ENV['access_token'] %>

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default
