default: &default
  appid: "wx799b2d765bf4b9ac"
  secret: "12cb0b486187ff17e90a05edbdfcd837"
  token:  "ljh861117wss900331"
  access_token: "/var/tmp/wechat_access_token"

production:
  appid: <%= ENV['WECHAT_APPID'] %>
  secret: <%= ENV['WECHAT_APP_SECRET'] %>
  token:   <%= ENV['WECHAT_TOKEN'] %>
  access_token:  <%= ENV['WECHAT_ACCESS_TOKEN'] %>

development:
  <<: *default
  trusted_domain_fullname: "http://your_dev.proxy.qqbrowser.cc"

test:
  <<: *default
