default: &default
  appid:    ENV["WECHAT_APP_ID"]
  secret:   ENV["WECHAT_APP_SECRET"]
  token:    ENV["WECHAT_TOKEN"]
  encrypt_mode: true
  encoding_aes_key:  ENV["WECHAT_ENCODING_AES_KEY"]

production:
  appid:      ENV["WECHAT_APP_ID"]
  secret:     ENV["WECHAT_APP_SECRET"]
  token:      ENV["WECHAT_TOKEN"]
  timeout:    30,
  skip_verify_ssl: true
  encrypt_mode: true
  encoding_aes_key:  ENV["WECHAT_ENCODING_AES_KEY"]

development:
  <<: *default

test:
  <<: *default
